### ISSUE TITLE
Issue ...

### ISSUE THREAD

**Issue by OzZy02100** [dethredic/WC3StreamerOverlay#10]
Hi, after do all the things like you said, i have this error

Exception in thread Thread-2:
Traceback (most recent call last):
  File "site-packages\scapy\arch\windows\__init__.py", line 891, in dev_from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "bnet_player_monitor.py", line 84, in run
  File "site-packages\scapy\sendrecv.py", line 836, in sniff
  File "site-packages\scapy\arch\pcapdnet.py", line 461, in __init__
  File "site-packages\scapy\arch\windows\__init__.py", line 997, in open_pcap
  File "site-packages\scapy\arch\windows\__init__.py", line 966, in pcapname
  File "site-packages\scapy\arch\windows\__init__.py", line 894, in dev_from_name
ValueError: Unknown network interface None

I have try to recreate the media source, to refresh cache, or to restart computer too.

Thanks you in advance.

**Comment by dethredic** [comment]
Can you try running the program as administrator?
